# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Chadri-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Chadri-iOS
  pod 'Alamofire','~> 5.4.1'
  pod 'Kingfisher'
  pod 'NMapsMap'
end
